import { EnvProvider } from "@/contexts/EnvContext";
import { getEnv } from "@/env";
import { PropsWithChildren } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = async ({ children }: PropsWithChildren<unknown>) => {
  const env = getEnv();

  console.log(env);

  return (
    <html lang="en">
      <body>
        <EnvProvider env={env}>{children}</EnvProvider>
      </body>
    </html>
  );
};

export default RootLayout;
