import { EnvProvider } from "@/contexts/EnvContext";
import { client } from "env";
import { PropsWithChildren } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = async ({ children }: PropsWithChildren<unknown>) => (
  <html lang="en">
    <body>
      <EnvProvider env={client}>{children}</EnvProvider>
    </body>
  </html>
);

export default RootLayout;
