import { EnvProvider } from "@/contexts/EnvContext";
import { getEnv } from "env";
import { PropsWithChildren } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = async ({ children }: PropsWithChildren<unknown>) => {
  const { client } = await getEnv();

  return (
    <html lang="en">
      <body>
        <EnvProvider env={client}>{children}</EnvProvider>
      </body>
    </html>
  );
};

export default RootLayout;
